name: Continous Integration Pipeline


on:
  pull_request:
    branches: [dev]

jobs:
  build_pull_request:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: 19
      - run: npm ci
      - run: npm run build